name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build and publish all DLLs
      run: dotnet publish
    
    - uses: isbang/compose-action@v1.4.0
      with:
        compose-file: ./test/docker-compose/docker-compose.yml
        up-flags: --abort-on-container-exit=sftp
        services: |
          sftp
    
    - name: Test module
      id: test_module
      uses: zyborg/pester-tests-report@v1
      with:
        include_paths: test
        exclude_tags: skip_ci
        report_name: module_tests
        report_title: My Module Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: dump test results
      shell: pwsh
      run: |
        Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
        Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
        Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'
