name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install and start sftp
      shell: bash
      run: |
        echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
        apk add --no-cache openssh openssl shadow@community
        ssh-keygen -A
        useradd -ms /bin/bash -p "$(openssl passwd -1 pass)" foo
        chown root:root /home/foo
        chmod 755 /home/foo
        mkdir /home/foo/upload
        chmod 755 /home/foo/upload
        rm -rf /etc/ssh/sshd_config
        curl -sSL https://raw.githubusercontent.com/atmoz/sftp/master/files/sshd_config -o /etc/ssh/sshd_config
        /usr/sbin/sshd -D -e

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build and publish all DLLs
      run: dotnet publish
    
    - uses: isbang/compose-action@v1.4.0
      with:
        compose-file: ./test/docker-compose/docker-compose.yml
        up-flags: --exit-code-from sftp
        services: |
          sftp
    
    - name: Test module
      id: test_module
      uses: zyborg/pester-tests-report@v1
      with:
        include_paths: test
        exclude_tags: skip_ci
        report_name: module_tests
        report_title: My Module Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: dump test results
      shell: pwsh
      run: |
        Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
        Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
        Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'
